version: "3.8"

services:
  activemq:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: activemq
    ports:
      - "61616:61616" # สำหรับ TCP Connection (JMS)
      - "8161:8161"   # สำหรับ Web Console
    environment:
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: admin

  spring-app:
    image: openjdk:11
    container_name: spring-boot-app
    depends_on:
      - activemq
    ports:
      - "8080:8080"
    environment:
      SPRING_ACTIVEMQ_BROKER-URL: tcp://activemq:61616
      SPRING_ACTIVEMQ_USER: admin
      SPRING_ACTIVEMQ_PASSWORD: admin