version: '3.8'

services:
  activemq-artemis:
    container_name: artemis
    build: .
    restart: unless-stopped
    ports:
      - "61616:61616"  # สำหรับ JMS
      - "8161:8161"    # สำหรับ Web UI
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin
    volumes:
      - activemq_data:/var/lib/artemis
    networks:
      - activemq_network

volumes:
  activemq_data:

networks:
  activemq_network:
    driver: bridge